rss: rss.xml
name: Thomas Wenzel
description: Personal Blog
source: ./
dest: build
posts: posts
drafts: _drafts
ignore: ["README.md", ".git/*", "build/*", "Makefile", "todo.txt"]
link: https://thowenzel.github.io/
