sudo: false
language: rust

before_script:
  - cargo install --force --git https://github.com/cobalt-org/cobalt.rs.git
  - export PATH="$PATH:~/.cargo/bin"

script:
  - cobalt build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  local_dir: build
  target_branch: master
  on:
    branch: source
